- name: disablenodejs
  ansible.builtin.shell: dnf module disable nodejs -y
- name: enable nodejs
  ansible.builtin.shell: dnf module enable nodejs:18 -y
- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present
- name: copy backend service
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service
- name: add application user
  ansible.builtin.user:
    name: expense
- name: import common role
  ansible.builtin.import_role:
    name: common
    tasks_from: prereq
  vars:
    app_dir: /app
    component: backend
- name: download nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app
- name: install mysql
  ansible.builtin.dnf:
    name: mysql
    state: present
- name: load schema
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_HOST', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_USER', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_PASS', region='us-east-1' ) }} < /app/schema/backend.sql
- name: restart mysql
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes