- name: copy yum elastic repofile
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: installing filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

