- name: copy module
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml



- name: restart node exporter
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes


- name: copy grafana module
  ansible.builtin.template:
    src: grafana.service
    dest: /etc/yum.repos.d/grafana.repo

- name: install grafana
  ansible.builtin.systemd:
    name: grafana
    state: present

- name: restart grafana
  ansible.builtin.systemd:
    name: grafana
    state: restarted
    enabled: yes


