- name: copy module
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml



- name: restart node exporter
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes




