route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: sns
    sns_configs:
      - topic_arn: arn:aws:sns:us-east-1:684832353742:alerts
        sigv4:
        region: us-east-1
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

