groups:
  - name: {{ component }}-{{ env }}
    rules:
    - alert: CPUUsagealert
      expr: avg by (instance) (100 - (rate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)) > 70
      for: 1m
      labels:
        severity: warning
        component: {{ component }}
        env: {{ env }}
      annotations:
        summary: warning | cpu usage alert