groups:
- name: {{ component }}-{{env}}
    rules:
      - alert: CPUUsageAlertWarning
        expr: avg by (instance) (100 - (rate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)) > 70
        for: 1m
        labels:
          severity: warning
          component: {{ component }}
          env: {{ env }}
        annotations:
          summary: Warning | CPU Usage Alert
      - alert: CPUUsageAlertCritical
        expr: avg by (instance) (100 - (rate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)) > 90
        for: 1m
        labels:
          severity: critical
          component: {{ component }}
          env: {{ env }}
        annotations:
          summary: Critical | CPU Usage Alert
      - alert: MemoryUsageAlertCritical
        expr: ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes) * 100 > 90
        for: 1m
        labels:
          severity: critical
          component: {{ component }}
          env: {{ env }}
        annotations:
          summary: Critical | CPU Usage Alert
      - alert: MemoryUsageAlertWarning
        expr: ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes) * 100 > 70
        for: 1m
        labels:
          severity: warning
          component: {{ component }}
          env: {{ env }}
        annotations:
          summary: Warning | CPU Usage Alert
      - alert: NetworkBWMonitorWaitQueue
        expr: rate(node_ethtool_bw_in_allowance_exceeded[1m]) > 0
        for: 3m
        labels:
          severity: critical
          component: {{ component }}
          env: {{ env }}
        annotations:
          summary: Critical | Network Wait Queue High
      - alert: NginxServiceMonitor
        expr: node_systemd_unit_state{exported_name="nginx.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
          component: {{ component }}
          env: {{ env }}
        annotations:
          summary: Critical | Frontend Nginx Service Down